name: typed_buffer
description: Read and write typed data from binary buffer.
version: 2.3.1
homepage: https://github.com/tejainece/typed_buffer
authors:
- Ravi Teja Gudapati <tejaience@gmail.com>
- James Ots <code@jamesots.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.17.5
